// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KURAGE_Dice","status":true,"description":"Dice plugin","parameters":{"PicStart#":"1","DiceVar1":"1","DiceVar2":"2","DiceVar3":"3","DiceVar4":"4"}}
];
